pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/GosOmkar/devops-cicd-demo.git'
            }
        }

        stage('Build with Maven') {
            steps {
                sh 'cd app && mvn clean package'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t gosomkar/hello-world:latest ./app'
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-token', variable: 'DOCKER_TOKEN')]) {
                    sh """
                        echo "$DOCKER_TOKEN" | docker login -u gosomkar --password-stdin
                        docker push gosomkar/hello-world:latest
                    """
                }
            }
        }
    }
}

